name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: Install cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f horse "Run for cover, I am a HOrse" >> horse.txt

            - name: Test File Exists
              run: grep -i "horse" horse.txt

            - name: Read File
              run: cat horse.txt

            - name: List Repo Files
              run: ls -ltra
